In [ ]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
# Use tensorflow.keras.preprocessing.text instead of keras.preprocessing.text to import Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [ ]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [ ]:
tokenizer.document_count

10

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
sequences = pad_sequences(sequences,padding='post')

In [ ]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [ ]:
len(X_train[1])

189

In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=150)
X_test = pad_sequences(X_test,padding='post',maxlen=150)

In [ ]:
X_train[0]

array([   12,    16,    43,   530,    38,    76,    15,    13,  1247,
           4,    22,    17,   515,    17,    12,    16,   626,    18,
       19193,     5,    62,   386,    12,     8,   316,     8,   106,
           5,     4,  2223,  5244,    16,   480,    66,  3785,    33,
           4,   130,    12,    16,    38,   619,     5,    25,   124,
          51,    36,   135,    48,    25,  1415,    33,     6,    22,
          12,   215,    28,    77,    52,     5,    14,   407,    16,
          82, 10311,     8,     4,   107,   117,  5952,    15,   256,
           4, 31050,     7,  3766,     5,   723,    36,    71,    43,
         530,   476,    26,   400,   317,    46,     7,     4, 12118,
        1029,    13,   104,    88,     4,   381,    15,   297,    98,
          32,  2071,    56,    26,   141,     6,   194,  7486,    18,
           4,   226,    22,    21,   134,   476,    26,   480,     5,
         144,    30,  5535,    18,    51,    36,    28,   224,    92,
          25,   104,

In [ ]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(150,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#SimpleRNN(32, input_shape=(150,1), return_sequences=False)

#This is a Simple RNN layer with 32 hidden units (neurons).

#Input shape: (150, 1) → This means the input sequence has 150 time steps,
# with 1 feature per time step.

#return_sequences=False → The RNN will return only the last hidden state,
#not the entire sequence.

#Dense(1, activation='sigmoid')

#A fully connected (Dense) layer with 1 neuron.

#Uses sigmoid activation → This is typically used for binary classification
 #(output between 0 and 1).#

In [ ]:
 #Explanation of Parameters (Param #)
#SimpleRNN (32 units):

#32 * (1 + 32) + 32 = 1088 (weights + biases).

#Dense (1 unit):

#32 * 1 + 1 = 33.



In [ ]:
print (model.get_weights()[0].shape)
#print model.get_weights()[1].shape
model.get_weights()[1].shape
#model.get_weights()[1]


(1, 32)


(32, 32)

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 47ms/step - accuracy: 0.5032 - loss: 0.7123 - val_accuracy: 0.5082 - val_loss: 0.6941
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 33s 37ms/step - accuracy: 0.5086 - loss: 0.6939 - val_accuracy: 0.4999 - val_loss: 0.6967
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 38ms/step - accuracy: 0.5037 - loss: 0.6943 - val_accuracy: 0.5066 - val_loss: 0.6933
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 40s 36ms/step - accuracy: 0.5057 - loss: 0.6943 - val_accuracy: 0.5153 - val_loss: 0.6934
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 38s 32ms/step - accuracy: 0.5098 - loss: 0.6936 - val_accuracy: 0.5001 - val_loss: 0.6937
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 32ms/step - accuracy: 0.5040 - loss: 0.6942 - val_accuracy: 0.5152 - val_loss: 0.6930
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 32ms/step - accuracy: 0.5095 - loss: 0.6931 - val_accuracy: 0.5015 - val_loss: 0.6946
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 25s 31ms/step - accuracy: 0.5089 - loss: 0.6934 - 

In [ ]:
pred = model.predict(X_test)
print(pred)



782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step
[[0.5358566 ]
 [0.48532432]
 [0.48532432]
 ...
 [0.48569742]
 [0.48567277]
 [0.48532432]]


In [ ]:
predictions = model.predict(sequences)

predictions


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[0.49433652],
       [0.5018606 ],
       [0.45512798],
       [0.6447934 ],
       [0.5738852 ],
       [0.5187205 ],
       [0.5234106 ],
       [0.5283814 ],
       [0.5754194 ],
       [0.54939395]], dtype=float32)

In [ ]:
test_data = np.random.rand(1, 150, 1)  # A random test sample with shape (1, 150, 1)

# 3️⃣ Predict
prediction = model.predict(test_data)

# 4️⃣ Interpret the result
print("Raw Prediction Output:", prediction)
print("Final Prediction (Binary):", 1 if prediction > 0.5 else 0)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Raw Prediction Output: [[0.53689444]]
Final Prediction (Binary): 1
